steps:
- name: gcr.io/cloud-builders/gsutil
  id: Sync composer bucket with dags folder.
  args: ["rsync", "-r", "-d", "./dags", "gs://$_DAG_BUCKET/dags/rawan"]
options:
  logging: CLOUD_LOGGING_ONLY

